# Generated by Django 2.2.2 on 2019-06-29 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nc',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
